$ApprovedApps = @(
    "1527c705-839a-4832-9118-54d4Bd6a0c89           "
    "c5e2524a-ea46-4f67-841f-6a9465d9d515           "
    "E2A4F912-2574-4A75-9BB0-0D023378592B           "
    "F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE           "
    "InputApp                                       "
    "Microsoft.AAD.BrokerPlugin                     "
    "Microsoft.AccountsControl                      "
    "Microsoft.AsyncTextService                     "
    "Microsoft.BioEnrollment                        "
    "Microsoft.CredDialogHost                       "
    "Microsoft.ECApp	                              "
    "Microsoft.LockApp	                            "
    "Microsoft.MicrosoftEdgeDevToolsClient	        "
    "Microsoft.PPIProjection	                      "
    "Microsoft.Win32WebViewHost	                    "
    "Microsoft.Windows.Apprep.ChxApp	              "
    "Microsoft.Windows.AssignedAccessLockApp	      "
    "Microsoft.Windows.CallingShellApp	            "
    "Microsoft.Windows.CapturePicker	              "
    "Microsoft.Windows.CloudExperienceHost	        "
    "Microsoft.Windows.ContentDeliveryManager	      "
    "Microsoft.Windows.NarratorQuickStart	          "
    "Microsoft.Windows.OOBENetworkCaptivePortal	    "
    "Microsoft.Windows.OOBENetworkConnectionFlow    "
    "Microsoft.Windows.ParentalControls	            "
    "Microsoft.Windows.PeopleExperienceHost	        "
    "Microsoft.Windows.PinningConfirmationDialog    "
    "Microsoft.Windows.SecHealthUI	                "
    "Microsoft.Windows.SecureAssessmentBrowser	    "
    "Microsoft.Windows.XGpuEjectDialog	            "
    "Microsoft.XboxGameCallableUI	                  "
    "Windows.CBSPreview	                            "
    "windows.immersivecontrolpanel	                "
    "Windows.PrintDialog	                          "
    "RealtekSemiconductorCorp.RealtekAudioContro    "
    "Microsoft.NET.Native.Runtime.1.4	              "
    "Microsoft.NET.Native.Runtime.1.4	              "
    "Microsoft.NET.Native.Framework.1.3	            "
    "Microsoft.NET.Native.Framework.1.3	            "
    "Microsoft.Services.Store.Engagement	          "
    "Microsoft.NET.Native.Runtime.1.7	              "
    "Microsoft.NET.Native.Framework.1.7	            "
    "Microsoft.UI.Xaml.2.0	                        "
    "Microsoft.NET.Native.Runtime.1.7	              "
    "Microsoft.NET.Native.Framework.1.7	            "
    "Microsoft.Advertising.Xaml	                    "
    "Microsoft.Windows.StartMenuExperienceHost	    "
    "Microsoft.Windows.ShellExperienceHost	        "
    "Microsoft.VCLibs.140.00	                      "
    "Microsoft.VCLibs.140.00	                      "
    "AppUp.IntelGraphicsControlPanel	              "
    "Microsoft.Windows.Cortana	                    "
    "Microsoft.MicrosoftEdge	                      "
    "Microsoft.UI.Xaml.2.0	                        "
    "Microsoft.UI.Xaml.2.2	                        "
    "Microsoft.UI.Xaml.2.1	                        "
    "Microsoft.UI.Xaml.2.2	                        "
    "Microsoft.UI.Xaml.2.1	                        "
    "Microsoft.NET.Native.Runtime.2.2	              "
    "Microsoft.NET.Native.Runtime.2.2	              "
    "Microsoft.UI.Xaml.2.3	                        "
    "Microsoft.UI.Xaml.2.3	                        "
    "Microsoft.NET.Native.Runtime.2.2	              "
    "Microsoft.Services.Store.Engagement	          "
    "Microsoft.UI.Xaml.2.4	                        "
    "Microsoft.UI.Xaml.2.4	                        "
    "Microsoft.ScreenSketch	                        "
    "Microsoft.MSPaint	                            "
    "Microsoft.NET.Native.Framework.2.2	            "
    "Microsoft.NET.Native.Framework.2.2	            "
    "Microsoft.Getstarted	                          "
    "Microsoft.VCLibs.110.00.UWPDesktop	            "
    "Microsoft.VCLibs.110.00.UWPDesktop	            "
    "Microsoft.VCLibs.120.00.UWPDesktop	            "
    "Microsoft.VCLibs.120.00.UWPDesktop	            "
    "Microsoft.WindowsSoundRecorder	                "
    "Microsoft.UI.Xaml.2.5	                        "
    "Microsoft.UI.Xaml.2.5	                        "
    "Microsoft.DirectXRuntime	                      "
    "Microsoft.DirectXRuntime	                      "
    "Microsoft.WindowsCalculator	                  "
    "1527c705-839a-4832-9118-54d4Bd6a0c89	          "
    "c5e2524a-ea46-4f67-841f-6a9465d9d515	          "
    "E2A4F912-2574-4A75-9BB0-0D023378592B	          "
    "F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE	          "
    "Microsoft.AAD.BrokerPlugin	                    "
    "Microsoft.AccountsControl	                    "
    "Microsoft.AsyncTextService	                    "
    "Microsoft.BioEnrollment	                      "
    "Microsoft.CredDialogHost	                      "
    "Microsoft.ECApp	                              "
    "Microsoft.LockApp	                            "
    "Microsoft.MicrosoftEdgeDevToolsClient	        "
    "Microsoft.Win32WebViewHost	                    "
    "Microsoft.Windows.Apprep.ChxApp	              "
    "Microsoft.Windows.AssignedAccessLockApp	      "
    "Microsoft.Windows.CallingShellApp	            "
    "Microsoft.Windows.CapturePicker	              "
    "Microsoft.Windows.ContentDeliveryManager	      "
    "Microsoft.Windows.NarratorQuickStart	          "
    "Microsoft.Windows.OOBENetworkCaptivePortal	    "
    "Microsoft.Windows.OOBENetworkConnectionFlow    "
    "Microsoft.Windows.ParentalControls	            "
    "Microsoft.Windows.PeopleExperienceHost	        "
    "Microsoft.Windows.PinningConfirmationDialog    "
    "Microsoft.Windows.Search	                      "
    "Microsoft.Windows.SecHealthUI	                "
    "Microsoft.Windows.SecureAssessmentBrowser	    "
    "Microsoft.Windows.StartMenuExperienceHost	    "
    "Microsoft.Windows.XGpuEjectDialog	            "
    "Microsoft.XboxGameCallableUI	                  "
    "MicrosoftWindows.UndockedDevKit	              "
    "NcsiUwpApp	                                    "
    "Windows.CBSPreview	                            "
    "Microsoft.VCLibs.140.00	                      "
    "Microsoft.MicrosoftEdge	                      "
    "Microsoft.Windows.CloudExperienceHost	        "
    "MicrosoftWindows.Client.CBS	                  "
    "Microsoft.StorePurchaseApp	                    "
    "Microsoft.Windows.Photos	                      "
    "Microsoft.Windows.ShellExperienceHost	        "
    "Microsoft.VCLibs.140.00.UWPDesktop	            "
    "Microsoft.VCLibs.140.00.UWPDesktop	            "
    "Microsoft.VCLibs.140.00                        "
    "Microsoft.VCLibs.140.00                        "
    "Microsoft.549981C3F5F10                        "
    "Microsoft.UI.Xaml.2.7                          "
    "Microsoft.UI.Xaml.2.7                          "
    "Microsoft.XboxIdentityProvider                 "
    "AppUp.IntelOptaneMemoryandStorageManagement    "
    "AppUp.IntelGraphicsExperience                  "
    "Microsoft.UI.Xaml.2.6	                        "
    "Microsoft.UI.Xaml.2.6	                        "
    "Microsoft.MicrosoftStickyNotes	                "
    "Microsoft.DesktopAppInstaller	                "
    "Microsoft.GamingServices	                      "
    "Microsoft.WindowsStore	                        "
    "KDEe.V.Okular                                  " 
    "Microsoft.MicrosoftEdge.Stable                 "
    "RealtekSemiconductorCorp.RealtekAudioControl   "
    "Microsoft.WindowsCamera                        "

)
$ExcludeFilter = $ApprovedApps -join "|" -replace '\s',''

foreach ( $PkgX in Get-Appxpackage -allusers ) {
    if ( $PkgX.Name -notmatch $ExcludeFilter ) {
        $PkgX | Remove-Appxpackage -AllUsers -ErrorAction SilentlyContinue
    }
}

foreach ( $PkgPro in Get-AppxProvisionedPackage -Online ) {
    if ( $PkgPro.Name -notmatch $ExcludeFilter ) {
        $PkgPro | Remove-AppxProvisionedPackage -AllUsers -Online -ErrorAction SilentlyContinue
    }
}
